name: Deploy

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$DEPLOY_URL"
